sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5.6'
  - '4.1'
  - '4.0'
before_script:
  - npm prune
script:
  - npm run clean
  - npm test
  - npm run build
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
